POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTM3MWI2OTJhZjlkMDI2MWFiYWY4MyIsInVzZXJuYW1lIjoiVXNlcm5hbWUyIiwiaWF0IjoxNjUzOTAwNzA2LCJleHAiOjE2NTQ1MDU1MDZ9.4gkPE1ufG7zEkrqFzlg4LyyyixofrQUWjcwbWyIGXIc

{
    "content": "contenido Nota Con usuario ",
    "important": true,
    "userId":"629371b692af9d0261abaf83"
}