POST http://localhost:3001/api/users
content-type: application/json

{
    "name": "Name",
    "surnames": "surnames",
    "DNI": "dni",
    "phone": 123456789,
    "email": "email",
    "password" : "12345678"
}