GET http://localhost:3001/api/users/hijos/6294f48a5fd13bb9d9665565
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTRmNDhhNWZkMTNiYjlkOTY2NTU2NSIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NDM1MTQyOSwiZXhwIjoxNjU0OTU2MjI5fQ.6mPp-vK9O7yJDh4HJIP7-83Js_2EAkwxOItoUvq0YBY
