GET http://localhost:3001/api/users/hijos/62a0cb7fa42eef27067a91e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTBjYjdmYTQyZWVmMjcwNjdhOTFlNyIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NTcxODI0NiwiZXhwIjoxNjU2MzIzMDQ2fQ.89vW9DhRq8gP7xI2ikd0aLT-UmGYvRq08QBdDZU-2iw
