POST http://localhost:3001/api/users/fav/62a1df7fa03b4c99de8fd643
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTBjYjdmYTQyZWVmMjcwNjdhOTFlNyIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NDc5NjUwNCwiZXhwIjoxNjU1NDAxMzA0fQ.-OyyLJy8kLKvprjDJQOduG-txjfmzoI6pqbuOb43baU

{
    "guards":"62a1df7fa03b4c99de8fd643"
}