POST http://localhost:3001/api/users
content-type: application/json

{
    "name": "Landd",
    "surnames": "apellidod",
    "DNI": "47415554N",
    "phone": "987654321",
    "email": "camado.alumnoww@iesrafaelalberti.es",
    "password": "12345678"
    
    
}