PUT  http://localhost:3001/api/users/fav/62a0cb7fa42eef27067a91e7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTBjYjdmYTQyZWVmMjcwNjdhOTFlNyIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NTQwMTg0NywiZXhwIjoxNjU2MDA2NjQ3fQ.Cc-yLqd5-c_1AxaWx2MlRhOcLezLOX8T5z-RmNjs2MI

{
    "guards":"62a1df7fa03b4c99de8fd643"
}