PUT http://localhost:3001/api/users/62a0c650d9cea9ceea033883
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTBjYjdmYTQyZWVmMjcwNjdhOTFlNyIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NDc5NzEzNCwiZXhwIjoxNjU1NDAxOTM0fQ.leFC3bBgDH3HGnCbpKWGDhC680rEUPLLMJFSAWRO0Yg

{
    "name": "Otro Name",
    "surnames": "otro Surname"
}