POST http://localhost:3001/api/comments/addcomment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTBjYjdmYTQyZWVmMjcwNjdhOTFlNyIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY2Mzc0OTgzMSwiZXhwIjoxNjY0MzU0NjMxfQ.IxrbJEyELuGjTimO1HmcU0HvQZi2us7dJ9SdCxuygZE

{
    "from": "63076d7eb5b57609efa9964f",
    "to": "62aaeddf0512671d470ff8b8",
    "contenido":"Hola Gonzalo",
    "valoracion":5
}