POST http://localhost:3001/api/babyguards
content-type: application/json

{
    "name": "Guard",
    "surnames": "Apellidos",
    "DNI": "62333248N",
    "email": "usuario2@apellido9.com",
    "phone": "987654319",
    "dias": [false, false, false, false, false, false, false],
    "horarioinicio": "09:00",
    "horariofin": "17:00",

    "password": "12345678"
    
    
}