GET http://localhost:3001/api/babyguards/fav
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTRmNDhhNWZkMTNiYjlkOTY2NTU2NSIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NDE3OTI2MSwiZXhwIjoxNjU0Nzg0MDYxfQ.OLN1fxGM5sXjt49jKYU3f3I84ZRMTkWRdRdmNWnQPnQ

{
    "guards": [ "6294f01238d3e2b5f85cb448", "6294de40296b7d01b52de54c" ]
}