PUT http://localhost:3001/api/babyguards/62b2f3154d2112a74fdca4eb
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWFlZGRmMDUxMjY3MWQ0NzBmZjhiOCIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NTM3NTYzMywiZXhwIjoxNjU1OTgwNDMzfQ.A04ixg1aK7QbFzfKFz1Z4b8oHh7PZOPRsOUNy7V3emE

{
    "dias": [false, false, false, false, false, false, false],
    "horariofin": "17:00",
    "horarioinicio": "09:00",
    "name": "CesarCambio",
    "phone": "987654321",
    "surnames": "AmadoA",
    "cp":11402
}