POST http://localhost:3001/api/hijos
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTRmNDhhNWZkMTNiYjlkOTY2NTU2NSIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NDE5NTMyMiwiZXhwIjoxNjU0ODAwMTIyfQ.lMdQOGv_g9c4JVG9sbZWsa0zhdB-GMjhqRvL6Q8CDNA

{
    "name": "hijo1",
    "surnames": "surnames",
    "edad": "edad",
    "DNI": "12345678N",
    "alergenos": "",
    "necesidadesesp": "",
    "user": "6294f48a5fd13bb9d9665565"
}