GET http://localhost:3001/api/hijos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTBjYjdmYTQyZWVmMjcwNjdhOTFlNyIsImVtYWlsIjoiYW1hZG9jZXNhcjAyQGdtYWlsLmNvbSIsImlhdCI6MTY1NTYzNjM4OSwiZXhwIjoxNjU2MjQxMTg5fQ.C60R500OlTBghVTN55yaW9U3RM4_aea0TMiPk1D4eDw

